### ISSUE TITLE
Level Filtering (Minor Stuffs)

### ISSUE THREAD

**Issue by SulaimanAZ** [SamClassicPatch/SuperProject#8]
### First

In Level Filtering:

**Show all**
Shows Only The Default Visible Levels
**Show visible**
Shows All Hidden Levels

Their Functions Should Be _**Reversed**_ And:

**Show: Visible**
Should Be Option 1 (Default)
**Show: All**
Should Be Option 2

### Second

When Level Filtering Is Turned **Off**, The **Default** Filtering Settings Should Get **Applied**

**Comment by DreamyCecil** [comment]
"Show all" and "Show visible" text is in imperative mood that tells you what it *will do*, rather than what it *is currently doing*.

When level filtering is disabled, this setting still applies because it's based on an already existing `sam_bShowAllLevels` command from vanilla, which saves its state between sessions.

**Comment by SulaimanAZ** [comment]
> "Show all" and "Show visible" text is in imperative mood that tells you what it _will do_, rather than what it _is currently doing_.
> 
> When level filtering is disabled, this setting still applies because it's based on an already existing `sam_bShowAllLevels` command from vanilla, which saves its state between sessions.

About the labels, I think it is more consistent this way, this is just my point of view.
About the settings, I still think that the default setting should be applied at the same time as level filtering is being disabled, So that the player does not get stuck in a situation where there are no levels due to invisible inappropriate filter settings.
